export default {
  TOGGLE_MESSAGE: 'TOGGLE_MESSAGE',
  GET_POPULAR_MOVIES: 'GET_POPULAR_MOVIES',
  GET_UPCOMING_MOVIES: 'GET_UPCOMING_MOVIES',
  GET_SEARCHED_MOVIES: 'GET_SEARCHED_MOVIES',
  GET_GENRES: 'GET_GENRES',
  GET_MOVIE: 'GET_MOVIE'
};
